###### Thingspeak API ######

# feeds
DEFAULT_THINGSPEAK_FEEDS_INTERVAL_DAYS = 7
THINGSPEAK_FEEDS_LIST_MAX_NUM_RESULTS = 8000
THINGSPEAK_FEEDS_LIST_URL = 'http://thingspeak.com/channels/{}'

# channels
THINGSPEAK_CHANNELS_LIST_URL_TEMPLATE = 'https://api.thingspeak.com/users/{}/channels.json'
MATHWORKS_USER_ID = 'baurd'
THINGSPEAK_CHANNELS_LIST_URL = THINGSPEAK_CHANNELS_LIST_URL_TEMPLATE.format(MATHWORKS_USER_ID)
AIR_QUALITY_MONITOR_KEYWORD = 'AIRQO'
INACTIVE_MONITOR_KEYWORD = 'INACTIVE'